// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWX2024.AppLogic.EntityFramework;

public partial class User
{
    public int ObjectId { get; set; }

    public string Name { get; set; }

    public string ResourceId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public virtual ICollection<UserPlantCode> UserPlantCodes { get; set; } = new List<UserPlantCode>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}