// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWX2024.AppLogic.EntityFramework;

public partial class UserPlantCode
{
    public int ObjectId { get; set; }

    public int UserObjectId { get; set; }

    public string PlantCode { get; set; }

    public virtual User UserObject { get; set; }
}